EXE = huge.exe

LIB = 

PROJECT_PWD = D:/ST/cygwin64/home/ccore/bliu/makefiles/huge

INC_DIRS = $(PROJECT_PWD)/source/foo/inc \
$(PROJECT_PWD)/source/bar/inc

LINK_LIBS = foo bar

include $(PROJECT_PWD)/make.rule
